### ISSUE TITLE
Cannot find module '/app/index.js'

### ISSUE THREAD

**Issue by mrTangYun** [alekzonder/docker-puppeteer#27]
docker run --rm -v /root/www/app/index.js:/app/index.js alekzonder/puppeteer:latest
module.js:549
    throw err;
    ^

Error: Cannot find module '/app/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by mrTangYun** [comment]
i'm wrong
