### ISSUE TITLE
Error: EACCES: permission denied, open '/app/w.js'

### ISSUE THREAD

**Issue by JohnYuanhao** [alekzonder/docker-puppeteer#29]
I used the synology‘s docker.

`# docker run --shm-size 1G --rm -v /volume1/homes/lese/app:/app alekzonder/puppeteer:latest node w.js`
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/app/w.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:662:20)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
and w.js just `console.log(1)`

I don't seem to have permission when I log in with root and ssh

**Comment by JohnYuanhao** [comment]
already solved!

ssh:`sudo chown -R 999:999 /home/app`

Give the mapped folder permissions just fine.
