### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by eskimoblood** [alekzonder/docker-puppeteer#9]
The version `1.1.0` throws an `Error: spawn EACCES` when I try to launch puppeteer. Not sure if this important but I have puppeteer installed locally in my project.

**Comment by alekzonder** [comment]
@eskimoblood need more info, what javascript script you run inside docker, how you mount it your project scripts into container

paste here your `docker run ...` with all arguments

**Comment by Neoglyph** [comment]
Same here.
When trying to launch my script with the command: 
`docker run --shm-size 1G --rm -v /home/test/code/test:/app alekzonder/puppeteer:latest node index.js`

i get the following: 

```
{ Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at Function.launch (/app/node_modules/puppeteer/lib/Launcher.js:107:40)
    at <anonymous> code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
```

**Comment by isakatirci** [comment]
what is root password. help. sudo does not work!
